labtest: sl_node.o lab_17_unit_test.o
	g++ -Wall -g -o labtest sl_node.o lab_17_unit_test.o
	
lab3: sl_node.cpp
	g++ -Wall -g -c sl_node.cpp
	
lab3ut: lab_17_unit_test.cpp
	g++ -Wall -g -c lab_17_unit_test.cpp