lab7test: lab_7.o lab_7_unit_test.o
	g++ -Wall -g -o lab7 lab_7.o lab_7_unit_test.o

lab7: lab_7.cpp
	g++ -Wall -g -c lab_7.cpp
	
lab7: lab_7_unit_test.cpp
	g++ -Wall -g -c lab_7_unit_test.cpp
	
lab8test: lab8.o lab_8_unit_test.o
	g++ -Wall -g -o lab8 lab_7.o lab_8_unit_test.o

lab8: lab_7.cpp
	g++ -Wall -g -c lab_7.cpp
	
lab8: lab_7_unit_test.cpp
	g++ -Wall -g -c lab_7_unit_test.cpp