assignment1test: assignment_1.o assignment_1_unit_test.o
	g++ -Wall -g -o assignment1 assignment_1.o assignment_1_unit_test.o

assignment1: assignment_1.cpp
	g++ -Wall -g -c assignment_1.cpp
	
assignment1: assignment_1_unit_test.cpp
	g++ -Wall -g -c assignment_1_unit_test.cpp