labtest: Assignment3.o unittest.o
	g++ -Wall -g -o labtest Assignment3.o unittest.o
	
lab3: Assignment3.cpp
	g++ -Wall -g -c Assignment3.cpp
	
lab3ut: unittest.cpp
	g++ -Wall -g -c unittest.cpp
	
clean:
	rm *.o labtest