all: labtest

labtest: unittest
	g++ -Wall -std=c++11 -g -o labtest unittest.o
#	g++ -Wall –std=c++11 -g –o labtest unittest.o

unittest:
	g++ -Wall -std=c++11 -g -c unittest.cpp
#	g++ -Wall –std=c++11 -g –c unittest.cpp