labtest: Declarations.o Driver.o
	g++ -Wall -g -o labtest Declarations.o Driver.o
	
lab3: Declarations.cpp
	g++ -Wall -g -c Declarations.cpp
	
lab3ut: Driver.cpp
	g++ -Wall -g -c Driver.cpp
	
clean:
	rm *.o labtest