labtest: sl_node.o sl_list.o unittest.o
	g++ -Wall -g -o labtest sl_node.o sl_list.o unittest.o
	
lab3n: sl_node.cpp
	g++ -Wall -g -c sl_node.cpp
	
lab3: sl_list.cpp
	g++ -Wall -g -c sl_list.cpp
	
lab3ut: lab_18_unit_test.cpp
	g++ -Wall -g -c unittest.cpp