temptest: temperature.o lab_10_unit_test.o
	g++ -Wall -g -o temp temperature.o lab_10_unit_test.o

temp: temperature.cpp
	g++ -Wall -g -c temperature.cpp
	
temp: lab_10_unit_test.cpp
	g++ -Wall -g -c lab_10_unit_test.cpp